
---
point_cloud_fusion_node:
  ros__parameters:
    output_topic:     "/points_concat"
    input_topics:
      - "topic1"
      - "topic2"
    output_frame_id:  "/base_link"
    cloud_size:       55000
