# This is a template parameter file which can be copied and modified for
# a specific implementation
vehicle_interface:
  ros__parameters:
    cycle_time_ms: 10
    raw_command:
      name: "raw_command"
      match_count: 1
    # Only one of the three control command topics need be specified
    # basic_command:
    #   name: "vehicle_command"
    #   match_count: 1
    # high_level_command:
    #   name: "high_level_command"
    #   match_count: 1
    state_command:
      name: "state_command"
      match_count: 0
    odometry:
      name: "odometry"
      match_count: 1
    state_report:
      name: "state_report"
      match_count: 1
    state_machine:
      gear_shift_velocity_threshold_mps: 0.5
      acceleration_limits:
        min: -3.0
        max: 3.0
        threshold: 1.0
      front_steer_limits:
        min: -0.331
        max: 0.331
        threshold: 0.3
      time_step_ms: 100
      timeout_acceleration_mps2: 3.0
      state_transition_timeout_ms: 3000
      gear_shift_accel_deadzone_mps2: 0.5
